version: '3.8'

services:
  alpha:
    image: dkv
    hostname: node1
    command: ./main --hostname=alpha --nto_contact=beta:9000:10000,gamma:9000:10000,delta:9000:10000 --type=server
    ports:
      - "10000:10000"
      - "8080:8080"

    networks:
      - dvk-net
  beta:
    image: dkv
    hostname: node2
    command: ./main --hostname=beta --nto_contact=alpha:9000:10000,gamma:9000:10000,delta:9000:10000 --type=server
    ports:
      - "10001:10000"
      - "8081:8080"
    networks:
      - dvk-net

  gamma:
    image: dkv
    hostname: gamma

    command: ./main --hostname=gamma --nto_contact=alpha:9000:10000,beta:9000:10000,delta:9000:10000 --type=server
    ports:
      - "10002:10000"
      - "8082:8080"
    networks:
      - dvk-net

  delta:
    image: dkv
    hostname: delta

    command: ./main --hostname=delta --nto_contact=alpha:9000:10000,beta:9000:10000,gamma:9000:10000 --type=server
    ports:
      - "10003:10000"
      - "8083:8080"
    networks:
      - dvk-net

networks:
  dvk-net:
    driver: bridge