version: '3.8'

services:
  zookeeper:
    image: zookeeper:3.8.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
    command: >
      sh -c "
      zkServer.sh start-foreground &
      sleep 5 &&
      echo 'create /election \"\"' | zkCli.sh -server localhost:2181;
      wait"
