version: '3.8'

services:
  Rome_Center-Server:
    image: dkv
    hostname: Rome_Center-Server
    container_name: dkv-Rome_Center-Server
    command: >
      ./main
      --hostname=Rome_Center-Server
      --nto_contact=New_York_TimeSquare-Server:9000:10000,Madrid_PlazaMajor-Server:9000:10000
      --simulate_latency=1
      --mode=Causal
      --hash=md5
    ports:
      - "8080:8080"
    networks:
      - dvk-net

  New_York_TimeSquare-Server:
    image: dkv
    hostname: New_York_TimeSquare-Server
    container_name: dkv-New_York_TimeSquare-Server
    command: >
      ./main
      --hostname=New_York_TimeSquare-Server
      --nto_contact=Rome_Center-Server:9000:10000,Madrid_PlazaMajor-Server:9000:10000
      --simulate_latency=64
      --mode=Causal
      --hash=md5
    ports:
      - "8081:8080"
    networks:
      - dvk-net

  Madrid_PlazaMajor-Server:
    image: dkv
    hostname: Madrid_PlazaMajor-Server
    container_name: dkv-Madrid_PlazaMajor-Server
    command: >
      ./main
      --hostname=Madrid_PlazaMajor-Server
      --nto_contact=Rome_Center-Server:9000:10000,New_York_TimeSquare-Server:9000:10000
      --simulate_latency=12
      --mode=Causal
      --hash=md5
    ports:
      - "8082:8080"
    networks:
      - dvk-net

networks:
  dvk-net:
    driver: bridge
